sudo: false
language: ruby
rvm:
  - 2.5.2
cache: bundler
install:
  - gem update --system '3.3.10'
  - rvm use 2.3.0 --install --binary --fuzzy
  - gem install bundler --version '1.15.1'
  - bundle _1.15.1_ install
before_script:
  # Disable SSH server fingerprint verification
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  # Set deployment target to github pages
  - bundle exec rake setup_github_pages[$REPO]
  - cd _deploy
  - git config user.name "TravisCI"
  - git config user.email "gamussa@gmail.com"
  - git config --global push.default simple
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials
  - git pull origin master
script: bundle exec rake generate
after_script:
  # Workaround for travis not to try run rake on generated site
  - ! 'echo ''script: "ls *.html"'' > public/.travis.yml'
  # Deploy!
  - bundle exec rake deploy
env:
  global:
    - REPO="https://github.com/razbor-poletov/razbor-poletov.github.com.git"
    - secure: GWdAGUnCaXU+hiLzSrzSMS+0GKfmfO1WBzt/U8lrZTCGPIKOXYlAb5e3JcnCMXl4tgmegeiKnBjand5KeCS18rhLuh/o2XbXew8s0UWigO6+7xFSDb9REKF/uKCOnf/ePTn0dcruO2Rz4h4YlIPvZtDk+wyk0qHe2xdXlrVcfsU=
